
# IMPORT MODULES

In [1]:
import pandas as pd
import numpy as np

# LOAD DATASET - simple variale

In [2]:
df = pd.read_csv("./test.csv")
df.head()

x          y
0  77  79.775152
1  21  23.177279
2  22  25.609262
3  20  17.857388
4  36  41.849864

In [3]:
X = df["x"].values.reshape(-1,1)
y = df["y"].values

# BUILD MODEL

In [4]:
import linear_model
import imp
imp.reload(linear_model)

<module 'linear_model' from 'c:\\Users\\hyun\\workspace\\TIL\\ML\\6_linear_reegression\\6_homework\\linear_model\\linear_model.py'>

In [5]:
lr = linear_model.LinearRegression(fit_intercept=True)

In [6]:
lr.fit(X, y)

(array([[  1.,  77.],
        [  1.,  21.],
        [  1.,  22.],
        [  1.,  20.],
        [  1.,  36.],
        [  1.,  15.],
        [  1.,  62.],
        [  1.,  95.],
        [  1.,  20.],
        [  1.,   5.],
        [  1.,   4.],
        [  1.,  19.],
        [  1.,  96.],
        [  1.,  62.],
        [  1.,  36.],
        [  1.,  15.],
        [  1.,  65.],
        [  1.,  14.],
        [  1.,  87.],
        [  1.,  69.],
        [  1.,  89.],
        [  1.,  51.],
        [  1.,  89.],
        [  1.,  27.],
        [  1.,  97.],
        [  1.,  58.],
        [  1.,  79.],
        [  1.,  21.],
        [  1.,  93.],
        [  1.,  27.],
        [  1.,  99.],
        [  1.,  31.],
        [  1.,  33.],
        [  1.,  80.],
        [  1.,  28.],
        [  1.,  47.],
        [  1.,  53.],
        [  1.,  69.],
        [  1.,  28.],
        [  1.,  33.],
        [  1.,  91.],
        [  1.,  71.],
        [  1.,  50.],
        [  1.,  76.],
        [  1.,   4.],
        [ 

In [7]:
lr.intercept

-0.46181077366115164

In [8]:
lr.coef

array([1.01433536])

In [9]:
lr.predict(X)[:10]

array([77.64201157, 20.83923168, 21.85356704, 19.82489633, 36.05426201,
       14.75321955, 62.42698124, 95.90004796, 19.82489633,  4.609866  ])

# VALIDATION

In [10]:
from sklearn import linear_model
sk_lr = linear_model.LinearRegression(normalize=False)
sk_lr.fit(X, y)

LinearRegression()

In [11]:
sk_lr.intercept_ 

-0.4618107736611563

In [12]:
import numpy.testing as npt
npt.assert_almost_equal(sk_lr.intercept_, lr.intercept)

In [13]:
sk_lr.coef_

array([1.01433536])

In [14]:
sk_lr.coef_ 

array([1.01433536])

In [15]:
np.isclose(lr.coef, sk_lr.coef_)

array([ True])

In [16]:
lr.predict(X)[:10]

array([77.64201157, 20.83923168, 21.85356704, 19.82489633, 36.05426201,
       14.75321955, 62.42698124, 95.90004796, 19.82489633,  4.609866  ])

In [17]:
df_test = pd.read_csv("./train.csv")
df_test.head()

x          y
0  24  21.549452
1  50  47.464463
2  15  17.218656
3  38  36.586398
4  87  87.288984

In [18]:
X_test = df["x"].values.reshape(-1,1)

In [19]:
lr.predict(X_test)[:5]

array([77.64201157, 20.83923168, 21.85356704, 19.82489633, 36.05426201])

In [20]:
sk_lr.predict(X_test)[:5]

array([77.64201157, 20.83923168, 21.85356704, 19.82489633, 36.05426201])

# LOAD DATASET - multiple variables

In [21]:
df = pd.read_csv("./mlr09.csv")
df.head()

height_in_feet  weight_in_pounds  successful_field_goals  \
0             6.8               225                   0.442   
1             6.3               180                   0.435   
2             6.4               190                   0.456   
3             6.2               180                   0.416   
4             6.9               205                   0.449   

   percent_of_successful_free_throws  average_points_scored  
0                              0.672                    9.2  
1                              0.797                   11.7  
2                              0.761                   15.8  
3                              0.651                    8.6  
4                              0.900                   23.2

In [22]:
y = df["average_points_scored"].values

In [23]:
df.iloc[:,:-1].head()

height_in_feet  weight_in_pounds  successful_field_goals  \
0             6.8               225                   0.442   
1             6.3               180                   0.435   
2             6.4               190                   0.456   
3             6.2               180                   0.416   
4             6.9               205                   0.449   

   percent_of_successful_free_throws  
0                              0.672  
1                              0.797  
2                              0.761  
3                              0.651  
4                              0.900

In [24]:
X = df.iloc[:,:-1].values

In [25]:
X[:5]

array([[  6.8  , 225.   ,   0.442,   0.672],
       [  6.3  , 180.   ,   0.435,   0.797],
       [  6.4  , 190.   ,   0.456,   0.761],
       [  6.2  , 180.   ,   0.416,   0.651],
       [  6.9  , 205.   ,   0.449,   0.9  ]])

# RESCALED

In [26]:
mu_X = np.mean(X, axis=0)
std_X = np.std(X, axis=0)

rescaled_X = (X - mu_X) / std_X

In [27]:
rescaled_X[:5]

array([[ 0.46843663,  0.50336336, -0.12692668, -0.70404955],
       [-0.63137111, -0.99746237, -0.25187012,  0.55584824],
       [-0.41140956, -0.66394554,  0.12296022,  0.19299768],
       [-0.85133266, -0.99746237, -0.59100234, -0.91571238],
       [ 0.68839818, -0.1636703 , -0.00198323,  1.59400403]])

# VALIDATION

In [28]:
lr.fit(rescaled_X, y)

(array([[ 1.00000000e+00,  4.68436630e-01,  5.03363361e-01,
         -1.26926677e-01, -7.04049553e-01],
        [ 1.00000000e+00, -6.31371109e-01, -9.97462366e-01,
         -2.51870124e-01,  5.55848242e-01],
        [ 1.00000000e+00, -4.11409562e-01, -6.63945538e-01,
          1.22960218e-01,  1.92997677e-01],
        [ 1.00000000e+00, -8.51332657e-01, -9.97462366e-01,
         -5.91002339e-01, -9.15712383e-01],
        [ 1.00000000e+00,  6.88398177e-01, -1.63670295e-01,
         -1.98322933e-03,  1.59400403e+00],
        [ 1.00000000e+00, -4.11409562e-01,  5.03363361e-01,
         -3.23266380e-01,  3.84502142e-01],
        [ 1.00000000e+00, -6.31371109e-01, -8.30703952e-01,
          6.76281200e-01,  2.93789501e-01],
        [ 1.00000000e+00,  4.68436630e-01,  8.36880189e-01,
          3.54998049e-01,  8.21266711e-02],
        [ 1.00000000e+00,  6.88398177e-01,  8.36880189e-01,
         -2.51870124e-01,  7.67511072e-01],
        [ 1.00000000e+00,  2.48475082e-01,  3.08811878e-03,
    

In [29]:
lr.coef

array([-1.67779283,  0.28359762,  2.68586629,  1.12816882])

In [30]:
lr.intercept

11.790740740740738

In [31]:
sk_lr.fit(rescaled_X, y)

LinearRegression()

In [32]:
sk_lr.coef_

array([-1.67779283,  0.28359762,  2.68586629,  1.12816882])

In [33]:
sk_lr.intercept_

11.790740740740736