In [1]:
import numpy as np
import warnings
warnings.filterwarnings(action='ignore')

### 1번. n_size_ndarray_creation

In [2]:
def n_size_ndarray_creation(n, dtype=np.int):
    X = np.arange(n**2).reshape(n,n)
    return X
    
    
print(n_size_ndarray_creation(3,dtype=np.int))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 2번. zero_or_one_or_empty_ndarray

In [3]:
def zero_or_one_or_empty_ndarray(shape, type, dtype=np.int):
    if type == 0:
        X = np.zeros(shape=(shape,shape), dtype=dtype)
    elif type == 1:
        X = np.ones(shape=(shape,shape), dtype=dtype)
    elif type == 99:
        X = np.empty((shape,shape))
    return X

    
print(zero_or_one_or_empty_ndarray(4,99,dtype=np.int))

[[4.67296746e-307 1.69121096e-306 1.33511697e-306 1.11256817e-306]
 [1.06811422e-306 1.42417221e-306 1.11260619e-306 8.90094053e-307]
 [1.86919378e-306 1.06809792e-306 1.37962456e-306 1.69111861e-306]
 [1.78020169e-306 1.37961777e-306 7.56599807e-307 7.56599806e-307]]


### 3번. change_shape_of_ndarray

In [4]:
def change_shape_of_ndarray(X, n_row):
    X = np.array(X).reshape(n_row, int(np.array(X).size//n_row))
    return X


a = np.ones((32,32), dtype=np.int)
print(change_shape_of_ndarray(a,1))

[[1 1 1 ... 1 1 1]]


### 4번. concat_ndarray

In [5]:
def concat_ndarray(X_1, X_2, ax):
    # X_1, X_2 둘다 1차원(Vector)일 때
    if np.array(X_1).ndim == 1 and np.array(X_2).ndim ==1:
        try:
            X = np.concatenate((X_1, X_2), axis=ax)
        except ValueError:
            X = False
    # 그 외
    else:
        # X_1이 1차원일 때 -> 2차원으로
        if np.array(X_1).ndim==1:
            X_1 = np.expand_dims(X_1, axis=0)
        # X_2가 1차원일 때 -> 2차원으로
        if np.array(X_2).ndim==1:
            X_2 = np.expand_dims(X_2, axis=0)
        try:
            X = np.concatenate((X_1, X_2), axis=ax)
        except ValueError:
            X = False
    return X

a = np.array([1, 2])
b = np.array([5, 6, 7])
concat_ndarray(a, b, 0)
## 왜 반대로 나오지 ..?
concat_ndarray(a, b, 1)

False

### 5번. normalize_ndarray

In [6]:
def normalize_ndarray(X, ax=99, dtype=np.float32):
    if ax == 1:
        mean = X.mean(axis=ax)
        std = np.std(X, axis=ax)
        for i in range(len(X)):
            for j in range(len(X[i])):
                X[i][j] = (X[i][j]-mean[i]) / std[i]
    elif ax == 0:
        mean = X.mean(axis=ax)
        std = np.std(X, axis=ax)
        for i in range(len(X)):
            for j in range(len(X[i])):
                X[i][j] = (X[i][j]-mean[j]) / std[j]
    elif ax == 99:
        mean = X.mean()
        std = np.std(X)
        for i in range(len(X)):
            for j in range(len(X[i])):
                X[i][j] = (X[i][j]-mean) / std
    return X


X = np.arange(12, dtype=np.float32).reshape(6,2)
print(normalize_ndarray(X,99))

[[-1.593255   -1.3035723 ]
 [-1.0138896  -0.7242068 ]
 [-0.4345241  -0.14484136]
 [ 0.14484136  0.4345241 ]
 [ 0.7242068   1.0138896 ]
 [ 1.3035723   1.593255  ]]


### 6번. save_ndarray

In [7]:
def save_ndarray(X, filename="test.npy"):
  # 바탕화면에 저장
  np.save('C:/Users/hyun/Desktop/{0}'.format(filename), X)
  return True

a = np.arange(32, dtype=np.float32).reshape(4, -1)
filename = "test.npy"
save_ndarray(a, filename)
## 바탕화면에 저장된 파일 불러오기
np.load('C:/Users/hyun/Desktop/{0}'.format(filename))

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/hyun/Desktop/test.npy'

### 7번. boolean_index

In [ ]:
def boolean_index(X, condition):
    result = np.where(eval(str("X") + condition))
    return result

X = np.arange(32).reshape(4, -1)
print(X)
boolean_index(X, "== 3")

: 

### 8번. find_nearest_value

In [ ]:
def find_nearest_value(X, tv):
    gap = float('inf')
    result = 0
    for i in range(len(X)):
        if abs(X[i]-tv) < gap:
            gap = abs(X[i]-tv)
            result = X[i]
    return result

a = np.arange(10)
print(find_nearest_value(a,4))

: 

### 9번. get_n_largest_values

In [ ]:
def get_n_largest_values(X, n):
    X = np.sort(X)[::-1][:n]
    return X
    
X = np.random.uniform(0, 1, 5)
get_n_largest_values(X,3)

: 