#### **Numpy - Numerical python**

- 태도 : 다 외운다기 보다는 익숙해져야 좋은 정도
- 파이썬의 고성능 과학 계산용 패키지 같은 느낌
- Matrix와 Vector와 같은 Array연산을 위해서 사용
- **numpy는 하나의 데이터 type만 배열에 넣을 수 있음 (List와 차이점)**

In [69]:
import numpy as np
from IPython.display import Image
import warnings
warnings.filterwarnings(action='ignore')

test_array = np.array([1,4,5,8], float) # 하나의 dtype만 입력가능 !!!
print(test_array)
type(test_array) 

[1. 4. 5. 8.]


numpy.ndarray

#### **[ array creation - ndarry ]**

In [70]:
a = [1,2,3,4,5]
b = [5,4,3,2,1]
a[0] is b[-1]

True

In [71]:
a = np.array(a)
b = np.array(b)
a[0] is b[-1]

False

- list : 메모리 공간에 static한 공간에 저장되어 메모리의 주소가 같기 때문에 True
- numpy : 메모리 공간에 차례대로 새롭게 값을 저장하기 때문에 서로 다른 메모리 주소를 저장하게 된다.

#### **[ array shape ]**
- **.shape** : array의 크기, 형태 등에 대한 정보 확인
- 차원이 증가할 수록 shpae에서 element 순서가 하나씩 뒤로 밀림<br><br><br>
- **.ndim** : 배열의 차원 수
- **.size** : data의 갯수 (element의 갯수)

In [72]:
a = [[1,2,3], [4,5,6]]
b = np.array([1,4,5,"8"], float) # 이렇게하면 "8"은 자동으로 float으로 변환
np.array(a).shape
np.array(a).size

6

In [73]:
vector = [1,2,3,4]
np.array(vector, int).shape # dtype 써준다.

(4,)

In [74]:
matrix = [[1,2,5,8], [1,2,5,8], [1,2,5,8]]
np.array(matrix,int).shape # dimension 올라가면서 행,렬 출력순서 바뀜

(3, 4)

#### **[ numpy dtype ]**
- **.dtype** : data의 type을 지정해서 저장해줄수 있다.

In [75]:
a = np.array([[1,2,3], [4.5,5,6]], dtype=np.int8)

In [76]:
a.dtype

dtype('int8')

In [77]:
np.array([[1,2,3],[4.5,"5","6"]], dtype=np.float32).nbytes

24

#### **[ reshape ]**
- Array의 shape의 크기를 변경, element의 갯수는 동일
- **flatten** : 다차원 array를 1차원 array로 변환(벡터 형태로)

In [78]:
test_matrix = [[1,2,3,4], [1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [79]:
np.array(test_matrix).reshape(4,2)

array([[1, 2],
       [3, 4],
       [1, 2],
       [5, 8]])

In [80]:
np.array(test_matrix).reshape(2,-1)
# -1 : 나머지 인자로 인해 이미 해당 자리에 어떤 값이 올지 정해진다면 -1써도 됨

array([[1, 2, 3, 4],
       [1, 2, 5, 8]])

In [81]:
test_matrix = [[1,2,3,4], [1,2,5,8]]
np.array(test_matrix).shape
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8])

#### **[ indexing ]**

In [82]:
test_example = np.array([[1,2,3], [4.5,5,6]], int)
test_example

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
test_example[0][2]
test_example[0,2] # 윗줄이랑 같은내용

3

In [84]:
test_example[0,0] = 10
test_example

array([[10,  2,  3],
       [ 4,  5,  6]])

#### **[ Slicing ]**
- 파이썬에서의 list와 달리 열부분을 나눠서 slicing 가능
- matrix같이 2차원 배열 이상부터도 slicing 가능

In [85]:
test_example = np.array([[1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8]])
test_example

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [86]:
test_example[:, 2:] # test_example에서 값만 추출하기 때문에 test_example자체는 안변함

array([[5, 8],
       [5, 8],
       [5, 8],
       [5, 8]])

In [87]:
test_example[:, 1:3].shape

(4, 2)

In [88]:
test_example[:, 1:3]

array([[2, 5],
       [2, 5],
       [2, 5],
       [2, 5]])

In [89]:
test_example[1] # Vector 형식으로 출력
test_example[1:3] # Matrix 형식으로 출력

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [90]:
a = np.arange(100).reshape(10,10) # arange : range랑 비슷
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [91]:
a[:, -1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [92]:
a[:,::2] # a[행,열(start,end,step)] -> 모든 행에서 모든 열의 2칸 간격으로

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

#### **[ Creation Function ]**
- **arange** : array의 범위를 지정, 값의 list를 생성하는 명령어(range랑 비슷)

In [93]:
np.arange(30) # 파이썬에서 range랑 비슷

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [94]:
np.arange(0, 10, 0.5) # 0.5단위로도 할수있음

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [95]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

- **ones, zeros** : 1로 가득찬 배열,  0으로 가득찬 배열


In [96]:
np.zeros(shape=(10,), dtype = np.int8) # ones도 마찬가지

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

- empty : shape만 주어지고 비어있는 ndarray 생성(memory initialization되지는 않음)
- **ndarray** : 다차원 행렬 자료구조 클래스, list자료형과 동일한 출력형태를 가짐

In [97]:
np.empty((2,5))

array([[0.88141422, 0.3380589 , 0.88853409, 0.4228902 , 0.80275939],
       [0.90978595, 0.8411194 , 0.29354264, 0.72954372, 0.47902327]])

- something_like : 인자로 받는 ndarray의 shape크기 만큼의 array반환 (ones,zeros,empty로 많이 쓰임)

In [98]:
test_matrix = np.arange(100).reshape(5,-1)
test_matrix.shape

(5, 20)

In [99]:
np.ones_like(test_matrix) # 이런식으로 ~~~_like로 쓰임

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [100]:
np.empty_like(test_matrix)

array([[  109,    97,   116,   114,   105,   120,    32,    61,    32,
           91,    91,    49,    44,    50,    44,    53,    44,    56,
           93,    44],
       [   32,    91,    49,    44,    50,    44,    53,    44,    56,
           93,    44,    32,    91,    49,    44,    50,    44,    53,
           44,    56],
       [   93,    93,    10,   110,   112,    46,    97,   114,   114,
           97,   121,    40,   109,    97,   116,   114,   105,   120,
           44,   105],
       [  110,   116,    41,    46,   115,   104,    97,   112,   101,
           32,    35,    32,   100,   105,   109,   101,   110,   115,
          105,   111],
       [  110,    32, 50732, 46972, 44032, 47732, 49436,    32, 54665,
           44, 47148,    32, 52636, 47141, 49692, 49436,    32, 48148,
        45084,   595]])

- identity : 단위행렬을 생성

In [101]:
np.identity(n=3, dtype=np.int8)
np.identity(n=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

- eye : 대각선이 1인 행렬, k값으로 시작 index 조절가능

In [102]:
np.eye(3,5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

- diag : 대각 행렬의 값을 추출함

In [103]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)
np.diag(matrix,k=1)

array([1, 5])

- **random smapling** : 데이터 분포에 따른 sampling으로 array생성

In [104]:
np.random.uniform(0,1,10).reshape(2,5) # 0에서 1사이의 수를 10개

array([[0.33831098, 0.5184486 , 0.01299458, 0.78368647, 0.34756808],
       [0.23185339, 0.86618319, 0.45943382, 0.03026815, 0.4203347 ]])

In [105]:
np.random.exponential(scale=2, size=100)

array([ 0.07234881,  2.88641583,  0.03928743,  7.07111885,  0.48264943,
        0.22257095,  4.362406  ,  0.91584999,  4.03400661,  0.67161082,
        0.79415171,  1.89651319,  0.54196161,  0.58837106, 14.14249413,
        0.45854128,  1.46346936,  0.51364955,  6.33384445,  0.28294975,
        2.53699081,  1.58577465,  7.41089307,  1.25185405,  4.00385966,
        1.78088869,  0.12042851,  0.32313889,  0.69065871,  3.01606816,
        0.62608152,  0.38667706,  0.30266974,  0.20693609,  0.24932493,
        8.43487   ,  4.24026208,  0.07850304,  1.57464021,  0.74038345,
        0.35377796,  0.92237132,  0.10449651,  2.39905193,  2.66376411,
        1.41386968,  3.81575467,  1.62561039,  4.98762254,  0.84497583,
        1.87555635,  3.19758332,  2.95262078,  2.77847002,  0.79800616,
        6.58606569,  1.13266254,  0.41620746,  1.74022927,  4.45547541,
        0.15686427,  2.48936962,  0.14406947,  2.34587965,  2.48532904,
        0.30811632,  0.20666635,  2.74820523,  0.02485083,  0.88

#### **[operation functions]**
- <span style='background-color:#fff5b1'>**sum**</span> : ndarray의 element들의 합, list의 sum과 같은 기능

In [106]:
test_array = np.arange(1,11)
test_array.sum(dtype=np.float16)

55.0

- <span style='background-color:#fff5b1'>**axis**</span> : 모든 operation function을 실행할 때 기준이 되는 dimension축
- 새로 생성된 축(새로운 차원이 생길 때)이 axis = 0

In [1]:
test_array = np.arange(1,13).reshape(3,4)
tensor_order_tensor = np.array([test_array,test_array,test_array])
tensor_order_tensor
# tensor_order_tensor의 shape은 (3,3,4)일 때 앞에서 부터 axis=0은 3, axis=1은 3,axis=2는 4이다

NameError: name 'np' is not defined

In [108]:
tensor_order_tensor.sum(axis=2) # axis=0은 

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [109]:
tensor_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

- **mean, std, sqrt** 등

- <span style='background-color:#fff5b1'>**concatenate**</span> : numpy array를 붙이는 함수, axis로 어느방향으로 붙일지 결정

In [111]:
a = np.array([[1,2,3]])
b = np.array([[4,5,6]])
np.concatenate((a,b), axis=0) # axis 활용할 수도 있음

array([[1, 2, 3],
       [4, 5, 6]])

- np.vstack : 가로끼리 합침
- np.hstack : 세로끼리 합침

In [110]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b),)

array([[1, 2, 3],
       [4, 5, 6]])

In [113]:
a = np.array([[1,2,3]])
b = np.array([[4,5,6]])
np.concatenate((a,b), axis=1)

array([[1, 2, 3, 4, 5, 6]])

In [112]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

- operations b/t arrays : numpy는 array간의 기본적인 사칙연산을 지원
- Element-wise operaions : Array간 shape이 같을 때 일어나는 연산 <br>ex)곱셈의 경우 행렬의 곱셈이 아니라 같은 위치의 원소끼리만 곱해줌

In [114]:
test_a = np.array([[1,2,3], [4,5,6]], float)
test_a+test_a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [115]:
test_a * test_a

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

- <span style='background-color:#fff5b1'>**Dot product**</span> : Matrix의 기본 연산,내적, dot 함수 사용, 행렬의 곱셈처럼

In [116]:
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

- **transpose** : 전치행렬, 행과 열의 위치를 바꿔줌

In [117]:
test_a.transpose()
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

- <span style='background-color:#fff5b1'>**broadcasting**</span> : shape이 다른 배열 간 연산해주는 기능<br>
서로 shape이 다르면 한쪽에 맞추기 위해 갖고있는 내용을 쭉 늘림<br><br>
![img](https://ifh.cc/g/rBaSkv.jpg)

In [119]:
test_matrix = np.arange(1,13).reshape(4,3)
test_vector = np.arange(10,40,10)
test_matrix + test_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

#### **[ Numpy performance ]**
- for loop **<** list comprehension **<** numpy
- numpy가 단순 for loop보다 약 4배의 성능차이
- numpy는 c로 구현되어있어, dynamic typing을 포기하는대신 성능을 확보한 느낌

- **[ Compatisons(호환성) ]**
    -  All & Any
    - array의 데어터에 전부(and)또는 일부(or)가 조건에 만족 여부를 반환
    - array끼리도 비교함
    - logical_or, logical_and 등등도 있음

In [120]:
a = np.arange(10)
a < 4 # a에 있는 모든 원소에 대해 <4를 실시하여 boolean값 반환

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [121]:
np.any(a>5)
# a의 원소 중 하나라도 조건에 만족하면 True
np.all(a>5)
# a의 원소 전부가 조건에 만족해야 True
a = np.array([1,3,0])
np.logical_and(a >0, a < 3)
# 각 조건들의 T,F를 비교하여 logical하게 또 비교하여 boolean값 반환

array([ True, False, False])

- **np.where()** : 괄호 안에 조건 넣으면 해당값 혹은 인덱스값 반환됨<br><br>
- 사용하는 2가지 방법<br>
** NaN : Not a Number, 숫자가 존재하지 않는 값
<br>** Inf : Is finite number, 무한히 발산하는 값

In [122]:
# 1번째 방법 : np.where 기본 사용법 (인덱스만 반환)
a = np.arange(5, 15)
np.where(a > 10)
# -> (array([6, 7, 8, 9]),)

(array([6, 7, 8, 9], dtype=int64),)

In [123]:
# 2차원 어레이일 때
a = np.array([[15, 8, 12], [11, 7, 3]])
np.where(a > 10)

(array([0, 0, 1], dtype=int64), array([0, 2, 0], dtype=int64))

In [124]:
# 2번째 방법 : np.where 값 반환 응용 (조건 True, False 위치 브로드캐스팅)
a = np.array([[15, 8, 12], [11, 7, 3]])
np.where(a > 10, a, 10)
# a가 10보다 크면 그대로, 그렇지 않으면 10으로 설정

b = np.array([[0, -1, 2], [-2, -1, -3]])
np.where(a > 10, a * 2, b)
# a가 10보다 크면 2배, 그렇지 않으면 b의 해당 위치 값으로 설정

array([[30, -1, 24],
       [22, -1, -3]])

In [125]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [126]:
np.isfinite(a)

array([ True, False, False])

- **argmax & argmin** : array내의 최대값, 최소값의 index를 반환
- argsort() : array를 정렬하여 그에 해당하는 index를 반환

In [127]:
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a), np.argmin(a)

(5, 0)

In [128]:
# axis 기반의 반환
a = np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
np.argmax(a, axis=1), np.argmin(a, axis=0)


(array([3, 1, 1], dtype=int64), array([0, 0, 2, 2], dtype=int64))

In [129]:
a = np.array([1,2,4,5,8,78,23,3])
a.argsort()

array([0, 1, 7, 2, 3, 4, 6, 5], dtype=int64)

- boolean index : 특정 조건에 따른 값을 배열 형태로 추출함, Comparison operation 함수들도 모두 사용가능

In [130]:
test_array = np.array([1,4,0,2,3,8,9,7],float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [131]:
test_array[test_array > 3]

array([4., 8., 9., 7.])

In [132]:
condition = test_array < 3
test_array[condition]

array([1., 0., 2.])

#### **[ fancy index ]**
- numpy는 array를 index value로 사용해서 값 추출
- take() : bracket index와 같은 효과

In [133]:
a = np.array([2,4,6,8], float)
b = np.array([0,0,1,3,2,1], int) # 반드시 integer로 선언(index로 쓰여야 하니까), a의 index를 넘어가면 에러 !
a[b] #bracket index, b배열의 값을 index로 하여 a의 값들을 추출
#b에서 첫번쨰 원소0이 a의 index가 0인 원소를 추출함

array([2., 2., 4., 8., 6., 4.])

In [134]:
a.take(b)

array([2., 2., 4., 8., 6., 4.])

In [135]:
# matrix 형태도 가능
a = np.array([[1,4],[9,16]], float)
b = np.array([0,0,1,1,0], int)
c = np.array([0,1,1,1,1], int)
a[b,c] # b가 row index로, c가 column index로 변환되어 표시함

array([ 1.,  4., 16., 16.,  4.])

#### **[ numpy data i/o(in/out) ]**
- **loadtxt & savetxt**
- text type의 데이터를 읽고, 저장하는 기능
- dellimeter : data를 자르는 기준

In [137]:
## load하는법
#a = np.loadtxt("./pupulations.txt") 
#a[:10]

In [140]:
## save 하는 법
#np.savetxt('int_data.csv',a_int, delimiter=",") 

In [138]:
## 파일 편집
## astype() : 인자로 받을 타입으로 values 변환 
#a_int = a.astype(int)
#a_int[:3]